## reference: http://docs.travis-ci.com/user/languages/r/

language: r
r: bioc-devel

cache: packages
bioc_required: true

r_packages:
  - WGCNA
  - dynamicTreeCut
  - igraph
  - RColorBrewer
  
bioc_packages:
  - AMOUNTAIN
  
after_failure:
  - ./travis-tool.sh dump_logs

## r_github_packages:
##   - jimhester/covr

after_success:
- Rscript -e 'library(covr); codecov()'

## notifications:
##   email:
##     on_success: change
##     on_failure: change